{{- if eq .Values.agentCollector.enabled true -}}
{{- if eq .Values.agentCollector.containerLogs.enrichK8sMetadata true -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "opentelemetry-collector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "opentelemetry-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
