{{- if or (and .Values.agentCollector.enabled (not (eq .Values.mode "deployment"))) (eq .Values.mode "daemonset") -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- include "opentelemetry-collector.annotations" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "opentelemetry-collector.selectorLabels" . | nindent 6 }}
      component: agent-collector
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-agent.yaml") . | sha256sum }}
        {{- include "opentelemetry-collector.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "opentelemetry-collector.selectorLabels" . | nindent 8 }}
        component: agent-collector
        {{- include "opentelemetry-collector.podLabels" . | nindent 8 }}
    spec:
      {{- $podValues := deepCopy .Values.agentCollector | mustMergeOverwrite (deepCopy .Values) }}
      {{- if eq .Values.mode "daemonset" }}
      {{- $podValues = deepCopy .Values }}
      {{- end }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "-agent" "isAgent" true }}
      {{- include "opentelemetry-collector.pod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
{{- $hostNetwork := .Values.agentCollector.hostNetwork -}}
{{- if eq .Values.mode "daemonset" }}
{{- $hostNetwork = .Values.hostNetwork -}}
{{- end }}
      hostNetwork: {{ $hostNetwork }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
{{- end }}
