{{- if not .Values.collectorCRD.generate -}}
{{- if .Values.targetAllocator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-targetallocator
  namespace: {{ template "opentelemetry-collector.namespace" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.targetAllocator.replicas }}
  {{- if .Values.minReadySeconds }}
  minReadySeconds: {{ .Values.targetAllocator.minReadySeconds }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opentelemetry-target-allocator.selectorLabels" . | nindent 6 }}
      component: target-allocator
  strategy:
    {{- if eq .Values.rollout.strategy "RollingUpdate" }}
    {{- with .Values.rollout.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.rollout.strategy }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-targetallocator.yaml") . | sha256sum }}
        {{- include "opentelemetry-collector.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "opentelemetry-target-allocator.selectorLabels" . | nindent 8 }}
        component: target-allocator
    spec:
      {{- if .Values.targetAllocator.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.targetAllocator.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.targetAllocator.affinity }}
      affinity:
        {{- toYaml .Values.targetAllocator.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.targetAllocator.tolerations }}
      tolerations:
        {{- toYaml .Values.targetAllocator.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "opentelemetry-collector.fullname" . }}-targetallocator
          {{- if .Values.targetAllocator.image.tag }}
          image: "{{ .Values.targetAllocator.image.repository }}:{{ .Values.targetAllocator.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.targetAllocator.image.digest}}
          image: "{{ .Values.targetAllocator.image.repository }}@{{ .Values.targetAllocator.image.digest }}"
          {{- end }}
          imagePullPolicy: {{ .Values.targetAllocator.image.pullPolicy }}
          args:
            {{- if .Values.targetAllocator.prometheusCR.enabled }}
            - --enable-prometheus-cr-watcher
            {{- end }}
          env:
          - name: OTELCOL_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP 
          {{- with .Values.targetAllocator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.targetAllocator.volumeMounts }}
          {{- toYaml .Values.targetAllocator.volumeMounts | nindent 10 }}
          {{- end }}
          - mountPath: /conf
            name: ta-internal
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: {{ .Values.targetAllocator.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.targetAllocator.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.targetAllocator.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.targetAllocator.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: {{ .Values.targetAllocator.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.targetAllocator.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.targetAllocator.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.targetAllocator.livenessProbe.failureThreshold }}
      volumes:
      {{- if .Values.targetAllocator.volumes }}
      {{- toYaml .Values.targetAllocator.volumes | nindent 6 }}
      {{- end }}
      - configMap:
          defaultMode: 420
          items:
          - key: targetallocator.yaml
            path: targetallocator.yaml
          name: {{ include "opentelemetry-collector.fullname" . }}-targetallocator
        name: ta-internal
      {{- if .Values.targetAllocator.serviceAccount }}
      serviceAccountName: {{ .Values.targetAllocator.serviceAccount | quote }}
      {{- else }}
      serviceAccountName: {{ include "opentelemetry-collector.serviceAccountName" . }}-targetallocator
      {{- end }}
{{- end }}
{{- end }}
