{{- if or .Values.standaloneCollector.enabled (eq .Values.mode "deployment") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- include "opentelemetry-collector.annotations" . | nindent 2 }}
spec:
{{- if not .Values.autoscaling.enabled }}
{{- $replicas := .Values.replicaCount -}}
{{- if .Values.standaloneCollector.enabled }}
  {{- $replicas = .Values.standaloneCollector.replicaCount -}}
{{- end }}
  replicas: {{ $replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "opentelemetry-collector.selectorLabels" . | nindent 6 }}
      component: standalone-collector
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "opentelemetry-collector.deployment-podAnnotations" . | nindent 8 }}
      labels:
        {{- include "opentelemetry-collector.selectorLabels" . | nindent 8 }}
        component: standalone-collector
        {{- include "opentelemetry-collector.deployment-podLabels" . | nindent 8 }}
    spec:
      {{- $podValues := deepCopy .Values.standaloneCollector | mustMergeOverwrite (deepCopy .Values) }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "" "isAgent" false }}
      {{- include "opentelemetry-collector.pod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
{{- end }}
