{{- include "opentelemetry-collector.validateAutoscaling" . -}}
{{- $legacyEnabled := .Values.autoscaling.enabled -}}
{{- $hpaEnabled := .Values.autoscaling.hpa.enabled -}}
{{- if and (or $legacyEnabled $hpaEnabled) (or (eq .Values.mode "deployment") (eq .Values.mode "statefulset")) }}
{{- $as := ternary .Values.autoscaling.hpa .Values.autoscaling $hpaEnabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  namespace: {{ template "opentelemetry-collector.namespace" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ include "opentelemetry-collector.hpaKind" . }}
    name: {{ include "opentelemetry-collector.fullname" . }}
  minReplicas: {{ $as.minReplicas }}
  maxReplicas: {{ $as.maxReplicas }}
  {{- if $as.behavior }}
  behavior:
    {{- toYaml $as.behavior | nindent 4 }}
  {{- end }}
  metrics:
  {{- if $as.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $as.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if $as.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $as.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- with $as.additionalMetrics }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
