{{- if .Values.priorityClass.create -}}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "opentelemetry-collector.priorityClassName" . }}
value: {{ .Values.priorityClass.priorityValue }}
globalDefault: false
description: "This priority class should be used for OpenTelemetry collector pods."
{{- end }}
