{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.metricsEndpoints (eq .Values.mode "deployment") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceMonitor.extraLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "opentelemetry-collector.selectorLabels" . | nindent 6 }}
      component: standalone-collector
  endpoints:
  {{- toYaml .Values.serviceMonitor.metricsEndpoints | nindent 2 }}
{{- end }}
