mode: deployment

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 70
    podsMetrics:
    - type: Pods
      pods:
        metric:
          name: "otelcol_k8s_collector_scrape_duration_seconds"
        target:
          type: AverageValue
          averageValue: "1"
    objectMetrics:
    - type: Object
      object:
        metric:
          name: "otelcol_k8s_collector_scrape_duration_seconds"
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: example-opentelemetry-collector
        target:
          type: AverageValue
          averageValue: "1"
    externalMetrics:
    - type: External
      external:
        metric:
          name: "otelcol_k8s_collector_scrape_duration_seconds"
        target:
          type: AverageValue
          averageValue: "1"
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
        - type: Percent
          value: 100
          periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 60
        policies:
        - type: Percent
          value: 100
          periodSeconds: 60

resources:
  limits:
    cpu: 2
    memory: 4Gi
