
opentelemetry-collector:
  config:
    exporters:
      otlp/my-own-observability-endpoint:
        endpoint: "my-observability-endpoint:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          exporters: [otlp/my-own-observability-endpoint, debug, spanmetrics]
        metrics:
          exporters: [otlp/my-own-observability-endpoint, debug]
        logs:
          exporters: [otlp/my-own-observability-endpoint, debug]
jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

