apiVersion: v2
name: opentelemetry-collector
version: 0.115.29
description: OpenTelemetry Collector Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/coralogix/opentelemetry-helm-charts
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
  - https://github.com/open-telemetry/opentelemetry-helm-charts
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
  - name: povilasv
appVersion: 0.126.0
