apiVersion: v2
name: opentelemetry-operator
<<<<<<< HEAD
version: 0.22.0
=======
version: 0.23.0
>>>>>>> 468f3ee ([BUMP] - operator 0.69/collector 0.71)
description: OpenTelemetry Operator Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: Allex1
  - name: dmitryax
  - name: TylerHelmuth
icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
appVersion: 0.69.0
