mode: daemonset
service:
  enabled: true
  ipDualStack:
    enabled: true
image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"
