mode: statefulset

image:
  repository: "otel/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

autoscaling:
  enabled: true
  mode: hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
