mode: daemonset

image:
  repository: "otel/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

global:
  image: busybox:latest
initContainers:
  - name: test
    command:
      - cp
    args:
      - /bin/sleep
      - /test/sleep
    image: "{{ .Values.global.image }}"
    volumeMounts:
      - name: test
        mountPath: /test

extraVolumes:
  - name: test
    emptyDir: {}

extraVolumeMounts:
  - name: test
    mountPath: /test

lifecycleHooks:
  preStop:
    exec:
      command:
      - /test/sleep
      - "5"

