mode: daemonset

initContainers:
  - name: test
    command:
      - cp
    args:
      - /bin/sleep
      - /test/sleep
    image: busybox:latest
    volumeMounts:
      - name: test
        mountPath: /test

extraVolumes:
  - name: test
    emptyDir: {}

extraVolumeMounts:
  - name: test
    mountPath: /test

lifecycleHooks:
  preStop:
    exec:
      command:
      - /test/sleep
      - "5"
