{{- if .Values.clusterRole.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opentelemetry-kube-stack.clusterRoleName" . }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - nodes/pods
  - nodes/metrics
  - nodes/stats
  - services
  - endpoints
  - pods
  - events
  - secrets
  - persistentvolumeclaims
  - persistentvolumes
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - servicemonitors
  - podmonitors
  - scrapeconfigs
  - probes
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
{{- include "opentelemetry-kube-stack.k8scluster.rules" . }}
{{- end }}
{{ range $_, $collector := $.Values.collectors -}}
{{- if $collector.enabled -}}
{{- if $.Values.defaultCRConfig.enabled }}
{{- $collector = (mergeOverwrite (deepCopy $.Values.defaultCRConfig) $collector) }}
{{- end }}
{{- $merged := (dict "Template" $.Template "Files" $.Files "Chart" $.Chart "clusterRole" $.Values.clusterRole "collector" $collector "Release" $.Release "fullnameOverride" $.Values.fullnameOverride "presets" $.Values.presets) }}
{{- $fullname := (include "opentelemetry-kube-stack.collectorFullname" $merged) }}
{{- if and $collector.enabled $collector.clusterRoleBinding.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "opentelemetry-kube-stack.clusterRoleName" $ }}
subjects:
- kind: ServiceAccount
  # quirk of the Operator
{{- if $collector.serviceAccount }}
  name: "{{ $collector.serviceAccount }}"
{{- else }}
  name: "{{ $fullname }}-collector"
{{- end }}
  namespace: {{ $.Release.Namespace }}
{{- if $collector.targetAllocator.enabled }}
- kind: ServiceAccount
{{- if $collector.targetAllocator.serviceAccount }}
  name: "{{ $collector.targetAllocator.serviceAccount }}"
{{- else }}
  name: {{ $fullname }}-targetallocator
{{- end }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if and $.Values.opAMPBridge.enabled $.Values.opAMPBridge.clusterRole.enabled }}
{{- $merged := (dict "Chart" $.Chart "clusterRole" $.Values.clusterRole "opAMPBridge" $.Values.opAMPBridge "Release" $.Release "fullnameOverride" $.Values.fullnameOverride) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opentelemetry-opamp-bridge.clusterRoleName" . }}
rules:
  - apiGroups:
      - opentelemetry.io
    resources:
      - opentelemetrycollectors
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - 'list'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opentelemetry-opamp-bridge.fullname" $merged }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "opentelemetry-opamp-bridge.clusterRoleName" . }}"
subjects:
  - kind: ServiceAccount
    # quirk of the Operator
    {{- if $.Values.opAMPBridge.serviceAccount }}
    name: "{{ $.Values.opAMPBridge.serviceAccount }}"
    {{- else }}
    name: "{{ (include "opentelemetry-opamp-bridge.fullname" $merged) }}-opamp-bridge"
    {{- end }}
    namespace: "{{ $.Release.Namespace }}"
{{- end }}
