apiVersion: v2
name: opentelemetry-target-allocator
version: 0.127.0
description: OpenTelemetry Target Allocator Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: atoulme
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 0.126.0
