mode: daemonset

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

daemonset:
  apiVersion: apps.kruise.io/v1alpha1

rollout:
  strategy: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    partition: 0
