apiVersion: v1
kind: Service
metadata:
  {{- with .Values.manager.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "opentelemetry-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  name: {{ template "opentelemetry-operator.fullname" . }}
  namespace: {{ template "opentelemetry-operator.namespace" . }}
spec:
  ports:
    - name: metrics
      {{- if .Values.metricsServer.secure }}
      port: {{ .Values.metricsServer.port }}
      {{- else }}
      port: {{ .Values.manager.ports.metricsPort }}
      {{- end }}
      protocol: TCP
      targetPort: metrics
  selector:
      {{- include "opentelemetry-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller-manager

{{- if or .Values.admissionWebhooks.create .Values.admissionWebhooks.secretName }}
---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.admissionWebhooks.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "opentelemetry-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  name: {{ template "opentelemetry-operator.fullname" . }}-webhook
  namespace: {{ template "opentelemetry-operator.namespace" . }}
spec:
  ports:
    - port: {{ .Values.admissionWebhooks.servicePort }}
      protocol: TCP
      targetPort: webhook-server
  selector:
      {{- include "opentelemetry-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller-manager
{{- end }}
