apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "opentelemetry-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ template "opentelemetry-operator.name" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{ if .Values.kubeRBACProxy.enabled }}
    - name: https
      port: {{ .Values.kubeRBACProxy.ports.proxyPort }}
      protocol: TCP
      targetPort: https
    {{- end }}
    - name: metrics
      port: {{ .Values.manager.ports.metricsPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager

{{- if or .Values.admissionWebhooks.create .Values.admissionWebhooks.secretName }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-operator
  name: {{ template "opentelemetry-operator.name" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: webhook-server
  selector:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
{{- end }}
