---
apiVersion: v2
name: opentelemetry-ebpf-profiler
version: 0.109.0
description: OpenTelemetry eBPF Profiler Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/coralogix/opentelemetry-helm-charts
  - https://github.com/open-telemetry/opentelemetry-helm-charts
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
  - name: iblancasa
appVersion: 0.121.0
