configMap:
  # Specifies whether a configMap should be created (true by default)
  create: false
  # Specifies an existing ConfigMap to be mounted to the pod
  # The ConfigMap MUST include the configuration via a key named 'targetallocator.yaml'. If not you can additionaly set existingKey to the desired one in the configmap
  existingName: "demo-configmap"
  existingKey: demo-key