apiVersion: v2
name: opentelemetry-ebpf
version: 0.1.5
description: OpenTelemetry eBPF Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-ebpf
maintainers:
  - name: dmitryax
  - name: jaronoff97
  - name: TylerHelmuth
  - name: nicolastakashi
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: v0.10.2
