{{- if and (.Values.configMap.create) (not .Values.configMap.existingName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helper.targetAllocatorConfigMapName" . }}
  namespace: {{ template "helper.namespace" . }}
  labels:
    {{- include "helper.commonLabels" . | nindent 4 }}
data:
  targetallocator.yaml: |
    {{-
      $defaultConfig := dict "collector_namespace" .Release.Namespace
    -}}
    {{- mergeOverwrite $defaultConfig .Values.targetAllocator.config | toYaml | nindent 4 }}
{{- end }}