{{- if .Values.targetAllocator.serviceAccount.create }}
apiVersion: v1
{{- if .Values.targetAllocator.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.targetAllocator.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ template "helper.targetAllocatorServiceAccountName" . }}
  namespace: {{ template "helper.namespace" . }}
  labels:
    {{- include "helper.commonLabels" . | nindent 4 }}
    app: {{ template "helper.name" . }}
    chart: {{ template "helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.targetAllocator.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.targetAllocator.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
