apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "helper.namespace" . }}
  name: {{ template "helper.fullname" . }}-ta
spec:
  selector:
    app: targetAllocator
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: http-port
