opentelemetry-collector:
  presets:
    logsCollection:
      enabled: false
      storeCheckpoints: false
    hostMetrics:
      enabled: false
    kubeletMetrics:
      enabled: false
    clusterMetrics:
      enabled: false
