---
apiVersion: v2
name: opentelemetry-ebpf-instrumentation
version: 0.1.8
description: OpenTelemetry eBPF instrumentation Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/coralogix/opentelemetry-helm-charts
  - https://github.com/open-telemetry/opentelemetry-helm-charts
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
  - name: nimrodavni78
appVersion: v0.3.0
