apiVersion: v2
name: opentelemetry-kube-stack
version: 0.5.0
description: |
  OpenTelemetry Quickstart chart for Kubernetes.
  Installs an operator and collector for an easy way to get started with Kubernetes observability.
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: Allex1
  - name: dmitryax
  - name: jaronoff97
  - name: TylerHelmuth
icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
# the appVersion stays aligned with the operator's latest version. If the collector has a patch
# release, the collector's latest patch will be manually overridden.
appVersion: 0.120.0
dependencies:
  - name: crds
    version: "0.0.0"
    condition: crds.install
  - name: opentelemetry-operator
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.84.2
    condition: opentelemetry-operator.enabled
  - name: kube-state-metrics
    version: "5.21.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.37.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
