name: Validate Chart Version Bump
permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'charts/opentelemetry-collector/Chart.yaml'
  workflow_dispatch:

jobs:
  validate-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate chart version bump
        run: |
          make validate-version-bump

